----     # to write two ymls in same file 

name: node-docker
on: 
  push: 
    branches:
    - master  #branches from which we want to build

jobs:
  checkout_to_branch: 
    name: checkout to repo job
    runs-on: ubuntu-latest
    steps: 
      - name: checkout to repo
        uses: actions/checkout@v3
      
      - name: setting up the environment
        id: setenv
        run: |  # pipe symbol to run directy linux commands

          if [[ "${{ github.ref }}" == "refs/heads/beta" || "${{ github.base_ref }}" == "beta" ]]; then
              echo "env=beta" >> $GITHUB_OUTPUT
              echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_OUTPUT
              echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_OUTPUT
          fi  

          # fi is to end

    outputs:
      env: ${{steps.setenv.outputs.env}}
      image_tag: ${{steps.setenv.outputs.IMAGE_TAG}}
      repo_name: ${{steps.setenv.outputs.REPO_NAME}}
  
  build:
    name: checkout to repo job
    runs-on: ubuntu-latest
    needs: [ checkout_to_branch ] #dependency on this previous job
    environment: ${{needs.checkout_to_branch.outputs.env}}
    steps: 
      - name: checkout to repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx        # installing docker before build
        uses: docker/setup-buildx-action@v2

      - name: build docker image
        run: docker build -t node-docker:${{needs.checkout_to_branch.outputs.image_tag}} .  

      - name: creating container
        run: docker run -d -P --name node-docker-latest node-docker:${{needs.checkout_to_branch.outputs.image_tag}}
        
